#!/usr/bin/env ruby
require_relative "../config/environment"

def config_for_app(application_config_file)
  lines = IO.read(application_config_file).split("\n")
  config = {}
  lines.each do |line|
    next if line =~ Regexp.new(Regexp.escape("GDS::SSO.config do |config|"))
    next if line =~ Regexp.new(/^end/)
    next if line =~ Regexp.new(/^(\s)+?$/)
    key = /config\.([^ ]+)/.match(line).to_a[1]
    value = /=[\s]+?['|"]([^'"]+)['|"]/.match(line).to_a[1]
    config[key] = value
  end
  config
end

def deverise_uri(uri)
  uri.gsub(/production.alphagov.co.uk/, "dev.gov.uk").gsub(/https:/, "http:")
end

def config_path_for_app(application)
  if application.name =~ /Content API/i 
    "../govuk_content_api/config/gds_sso_config.rb"
  else
    "../#{application.name.downcase}/config/initializers/gds-sso.rb"
  end
end

::Doorkeeper::Application.all.each do |application|
  if application.name =~ /(guides_test|Contact-o-Tron|licensify)/i
    puts "WARNING Skipping #{application.name}, as it doesn't exist or doesn't use gds-sso"
    next
  end
  
  local_config = config_for_app(config_path_for_app(application))

  application.redirect_uri = deverise_uri(application.redirect_uri)
  application.home_uri     = deverise_uri(application.home_uri)
  application.uid          = local_config["oauth_id"]
  application.secret       = local_config["oauth_secret"]
  puts "Updating application #{application.name}"
  application.save!
end
